### ISSUE TITLE
Consider using the WordPress-Docs ruleset

### ISSUE THREAD

**Issue by jeremyfelt** [a8cteam51/team51-configs#2]
#1 added sniffs for documentation, which I very much appreciate. I think it'd be worth considering using the [WordPress-Docs ruleset](https://github.com/WordPress/WordPress-Coding-Standards#standards-subsets) so that documentation matches [WordPress PHP documentation standards](https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/). My guess is that it's already very close, but there are likely some other detailed decisions made upstream that would be helpful. :)

**Comment by ahegyes** [comment]
We now extend the `WordPress-Docs` standard as of this week. Closing!
